POST http://localhost:3000/projetos
Content-Type: application/json

{
    "nomeEmpresa" : "  Gerdau ouro branco",
    "nomeProjeto" : "Linha de vida 1"
}

###

GET http://localhost:3000/projetos

###

PUT http://localhost:3000/projetos
Content-Type: application/json

{   
    "nomeEmpresa" : "gerdau divinopoliis",
    "nomeProjeto" : "Plataforma tandem.",
    "descricao" : "empresa de produção de aço e perfis.",
    "codigo" : "999999",
    "disciplina" : "mecânica"
}

###

DELETE http://localhost:3000/projetos/5e233db7fa7fed0a7cf4f0f9