runtime: nodejs12
basic_scaling:
  max_instances: 10

# Comentário no formato YAML
# Exemplo de outras configurações:

# handlers:
# Serve images as static resources.
# - url: /(.+\.(gif|png|jpg))$
#   static_files: \1
#   upload: .+\.(gif|png|jpg)$
#   application_readable: true

# Serve php scripts.
# - url: /(.+\.php)$
#   script: \1

# Os padrões de caminho de URL e arquivo usam a sintaxe de expressões regulares estendidas POSIX (https://en.wikipedia.org/wiki/Regular_expression), excluindo elementos e classes de compilação.