POST http://localhost:3333/projetos
Content-Type: application/json

{
    "cliente": "Gerdau",
    "nomeProjeto": "Linha de vida 1",
    "disciplinaMestre": "Engenharia Mecânica",
    "numPedido": "123123",
    "responsavel": "Barack Obama",
    "tipoEngenharia": "A melhor",
    "status": "Aguardando aprovação",
    "infoProjetos": [{
        "disciplinaDesenho": "Simulação ANSYS",
        "revisao": "a",
        "numFull": "321",
        "numCliente": "666",
        "formato": "A0",
        "descricao": "Deu tudo certo",
        "projetistaDesenho": "Vinícius Gajo",
        "verificadorDesenho": "Donald Trump"
    },{
        "disciplinaDesenho": "inventor",
        "revisao": "a",
        "numFull": "3333",
        "numCliente": "5555",
        "formato": "A0",
        "descricao": "Aguardando aprovação",
        "projetistaDesenho": "Vinícius Gajo",
        "verificadorDesenho": "Aécio neves"
    }],
    "arquivado": false
}

###

GET http://localhost:3333/projetos
Authorization: Bearer eyJhb1231OiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlNDJmMjasdaDM3YWNlMGI3NDdhZjc3NyIsImlhdCI6MTU4Mzc3MjM3NSwiZXhwIjoxNTgzODA4Mzc1fQ.P5doTX3wbBDqRvWgWn61fqMqBtCxdsadE4527mJjwE

###
PUT http://localhost:3333/projetos/5e4a7bea08a0571120595b54
Content-Type: application/json

{   
    "infoProjetos": [{
        "disciplinaDesenho": "autocad",
        "revisao": "a",
        "numFull": "7777",
        "numCliente": "88888",
        "formato": "A0",
        "descricao": "Aguardando aprovação",
        "projetistaDesenho": "Vinícius Gajo",
        "verificadorDesenho": "José Serra"
    }],
    "arquivado": true
}

###
DELETE http://localhost:3333/projetos/5e4a7617419bab111857c19b

###
GET http://localhost:3333/excel/5e56a35a6a5f940facdeb9cd