POST http://localhost:3333/projetos
Content-Type: application/json

{
    "nomeEmpresa" : "  Gerdau ouro branco",
    "nomeProjeto" : "Linha de vida 1"
}

###

GET http://localhost:3333/projetos

###

PUT http://localhost:3333/projetos/5e263f8392c6960b6c5001e0
Content-Type: application/json

{   
    "nomeEmpresa" : "gerdau divinopolis",
    "nomeProjeto" : "Plataforma tandem.",
    "descricao" : "empresa de produção de aço e perfis.",
    "codigo" : "999999",
    "disciplina" : "mecânica",
    "numNosso" : "123456"
}

###

DELETE http://localhost:3333/projetos/5e2342623f6fec1510006ff6