POST http://localhost:3333/login
Content-Type: application/json

{
    "email": "teste",
    "senha": "teste" 
}

###
POST http://localhost:3333/login/create
Content-Type: application/json

{
    "email": "teste",
    "senha": "teste"  
}

###
GET http://localhost:3333/login